language: python

cache:
  pip: true
  directories:
    - node_modules

python:
  - '3.5'

before_install:
  - nvm install 6.6.0

install: npm install

script:
    - npm test
    - cd server && py.test
