---
- name: enable mongodb
  systemd:
    daemon_reload: yes
    name: mongodb.service
    enabled: yes

- name: restart mongodb
  systemd:
    daemon_reload: yes
    name: mongodb.service
    state: restarted
