---
- name: Install Python
  apt:
    name: python3-pip
    state: latest

- name: Install virtualenv
  pip: executable=pip3 name=virtualenv state=latest

- name: Create virtualenv for eve
  command: virtualenv --no-site-packages --python python3 /var/eved/{{ domain_name }}/venv/
  args:
    creates: /var/eved/{{ domain_name }}/venv/

- name: Install wsgi file
  template:
    src: templates/uwsgi.ini.j2
    dest: /var/eved/uwsgi.ini
  notify:
    - restart eve

- name: Install Eve service
  template:
    src: templates/eved.service.j2
    dest: /lib/systemd/system/eved.service
  notify:
    - enable eve
    - restart eve

- name: Deploy eve application
  copy:
    src: ../server/
    dest: /var/www/{{ domain_name }}/
  notify:
    - restart eve
  tags: [deploy]

- name: Install python requirements
  command: /var/eved/{{ domain_name }}/venv/bin/pip install -r /var/www/{{ domain_name }}/requirements.txt
  notify:
    - restart eve
  tags: [deploy]
