---
- name: Compile js bundle locally
  command: yarn pre
  args:
    chdir: ..
  delegate_to: 127.0.0.1
  become: no
  tags: [compile]

- name: Deploy html
  copy:
    src: ../../index.html
    dest: /var/www/{{ domain_name }}/

- name: Deploy js bundle
  copy:
    src: ../../dist/bundle.js
    dest: /var/www/{{ domain_name }}/
