---
- hosts: typer
  become: true
  gather_facts: no

  pre_tasks:
    - raw: apt-get install -y python-simplejson

  roles:
    - letsencrypt
    - eve

  tasks:
    - name: Upgrade system
      apt: upgrade=dist update_cache=yes

    - name: Install MongoDB
      apt: name=mongodb state=latest

    - name: Compile js bundle locally
      command: node node_modules/webpack/bin/webpack.js -vpc --config webpack.config.prod.js
      delegate_to: 127.0.0.1
      become: no

    - name: Deploy html
      copy:
        src: ../index.html
        dest: /var/www/{{ domain_name }}/

    - name: Deploy js bundle
      copy:
        src: ../dist/bundle.js
        dest: /var/www/{{ domain_name }}/
